#ifndef RMIT2022C_EEET2482_LODGING_APP_SRC_UTILS_DATETIME_H_
#define RMIT2022C_EEET2482_LODGING_APP_SRC_UTILS_DATETIME_H_

namespace utils {

    class Datetime {

    };

} // utils

#endif //RMIT2022C_EEET2482_LODGING_APP_SRC_UTILS_DATETIME_H_
