#ifndef RMIT2022C_EEET2482_LODGING_APP_SRC_ENTITIES_ACCOUNT_ADMIN_H_
#define RMIT2022C_EEET2482_LODGING_APP_SRC_ENTITIES_ACCOUNT_ADMIN_H_

namespace account {

    class Admin {
        // TODO: Implement
    };

} // account

#endif //RMIT2022C_EEET2482_LODGING_APP_SRC_ENTITIES_ACCOUNT_ADMIN_H_
