name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: MinSizeRel
  BUILD_DIR: minsizerel
  BUILD_TARGET: lodging
  BUILD_TEST_TARGET: all-tests

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --target ${{env.BUILD_TARGET}} ${{env.BUILD_TEST_TARGET}}

    - name: Test
      working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
      run: ctest "--extra-verbose"
